name: Build

on: [workflow_dispatch]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Build for GMS2
        run: |
          msbuild . "/property:Configuration=GMS2 Release" /p:Platform=x86
          
      - name: Build for GMS2 x64 runtime
        run: |
          msbuild . "/property:Configuration=GMS2 Release" /p:Platform=x64
          
      - name: Upload GMS2 artifact
        uses: actions/upload-artifact@v2

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install GCC
        run: sudo apt-get install gcc-multilib g++-multilib
          
      - name: Build Linux x64/GMS2
        run: sh build_linux_gms2.sh

      - name: Upload Linux x64/GMS2
        uses: actions/upload-artifact@v2
        with:
          name: GMS2
          path: ./Steamworks.gml.so
          if-no-files-found: error

  build-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build for MacOS x64/GMS2
        run: sudo sh build_osx_gms2.sh
        
      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v2
